spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/arcane_arena
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080
